from app.config.schema import HootPRConfig
from app.platforms.base import FileDiff
from app.platforms.diff import build_file_diff
from app.review.stages.diff_filter import (
    SkippedFile,
    apply_budget,
    filter_files,
    glob_match,
    passes_path_filters,
)


def fd(path: str, added: list[str] | None = None, status: str = "modified") -> FileDiff:
    lines = added or ["x = 1"]
    patch = f"@@ -1,0 +1,{len(lines)} @@\n" + "".join(f"+{t}\n" for t in lines)
    return build_file_diff(path, patch, status)  # type: ignore[arg-type]


def cfg(**reviews: object) -> HootPRConfig:
    return HootPRConfig.model_validate({"reviews": reviews})


def test_glob_semantics() -> None:
    assert glob_match("src/a/b.snap", "**/*.snap")
    assert glob_match("b.snap", "**/*.snap")
    assert glob_match("src/api/x.py", "src/api/**")
    assert not glob_match("src/apix/x.py", "src/api/**")
    assert glob_match("deep/dir/file.snap", "*.snap")  # no slash: basename match (gitignore style)
    assert not glob_match("a.py", "")


def test_path_filters_include_and_exclude() -> None:
    assert not passes_path_filters("a/b.snap", ["!**/*.snap"])
    assert passes_path_filters("a/b.py", ["!**/*.snap"])
    assert passes_path_filters("src/x.py", ["src/**", "!src/gen/**"])
    assert not passes_path_filters("docs/x.md", ["src/**"])
    assert not passes_path_filters("src/gen/x.py", ["src/**", "!src/gen/**"])


def test_always_excluded_files() -> None:
    files = [
        fd("pnpm-lock.yaml"),
        fd("go.sum"),
        fd("assets/logo.png"),
        fd("vendor/lib/x.go"),
        fd("web/node_modules/p/i.js"),
        fd("dist/app.js"),
        fd("static/app.min.js"),
        fd("api/pb.go", ["// Code generated by protoc-gen-go. DO NOT EDIT."]),
        fd("src/huge.js", ["a" * 1500]),
        fd("old.py", status="removed"),
        build_file_diff("bin/tool", None, "added"),
        fd("src/app.py"),
    ]
    res = filter_files(files, cfg())
    assert [f.path for f in res.kept] == ["src/app.py"]
    reasons = {s.path: s.reason for s in res.skipped}
    assert reasons["pnpm-lock.yaml"] == "lockfile" and reasons["go.sum"] == "lockfile"
    assert reasons["assets/logo.png"] == "binary" and reasons["bin/tool"] == "binary"
    assert reasons["vendor/lib/x.go"] == "vendored" and reasons["dist/app.js"] == "vendored"
    assert reasons["web/node_modules/p/i.js"] == "vendored"
    assert reasons["static/app.min.js"] == "minified" and reasons["src/huge.js"] == "minified"
    assert reasons["api/pb.go"] == "generated" and reasons["old.py"] == "removed"


def test_vendored_prefix_is_directory_bounded() -> None:
    res = filter_files([fd("distribution/x.py"), fd("src/vendors.py")], cfg())
    assert [f.path for f in res.kept] == ["distribution/x.py", "src/vendors.py"]


def test_user_path_filters_are_applied() -> None:
    res = filter_files([fd("a/b.snap"), fd("a/b.py")], cfg(path_filters=["!**/*.snap"]))
    assert [f.path for f in res.kept] == ["a/b.py"]
    assert res.skipped[0].reason == "path_filter"


def test_budget_prefers_security_relevant_source_over_tests() -> None:
    files = [
        fd("tests/test_big.py", ["x"] * 50),
        fd("src/util.py", ["x"] * 30),
        fd("src/auth/login.py", ["x"] * 30),
    ]
    res = apply_budget(files, max_files=2, max_lines=10_000)
    assert [f.path for f in res.kept] == ["src/util.py", "src/auth/login.py"]  # original order kept
    assert res.skipped == [SkippedFile("tests/test_big.py", "over_budget")]


def test_budget_on_changed_lines_keeps_at_least_one_file() -> None:
    files = [fd("src/a.py", ["x"] * 80), fd("src/b.py", ["x"] * 30)]
    res = apply_budget(files, max_files=150, max_lines=50)
    assert [f.path for f in res.kept] == ["src/a.py"]
    assert apply_budget(files, max_files=150, max_lines=5000).skipped == []
