"""Diff filtering and the size budget (spec §7.1)."""

from __future__ import annotations

import re
from collections.abc import Sequence
from dataclasses import dataclass
from functools import lru_cache
from pathlib import PurePosixPath
from typing import Literal

from app.config.schema import HootPRConfig
from app.platforms.base import FileDiff

SkipReason = Literal[
    "lockfile",
    "binary",
    "generated",
    "minified",
    "vendored",
    "removed",
    "path_filter",
    "over_budget",
]
LOCKFILES = frozenset(
    {
        "package-lock.json",
        "npm-shrinkwrap.json",
        "pnpm-lock.yaml",
        "yarn.lock",
        "bun.lockb",
        "poetry.lock",
        "Pipfile.lock",
        "uv.lock",
        "pdm.lock",
        "go.sum",
        "Cargo.lock",
        "composer.lock",
        "Gemfile.lock",
        "packages.lock.json",
        "flake.lock",
        "mix.lock",
        "pubspec.lock",
        "Podfile.lock",
        "gradle.lockfile",
        "Package.resolved",
    }
)
BINARY_EXTS = frozenset(
    {
        ".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp", ".ico", ".svg", ".pdf", ".zip",
        ".gz", ".tgz", ".tar", ".bz2", ".xz", ".7z", ".jar", ".war", ".woff", ".woff2",
        ".ttf", ".otf", ".eot", ".mp3", ".mp4", ".mov", ".wav", ".so", ".dylib", ".dll",
        ".exe", ".bin", ".class", ".pyc", ".wasm", ".sqlite", ".db",
    }
)  # fmt: skip
VENDORED = ("vendor/", "node_modules/", "dist/")
GENERATED_MARKERS = ("@generated", "DO NOT EDIT", "Code generated by", "<auto-generated")
MINIFIED_LINE_CHARS = 1000
SECURITY_HINTS = re.compile(
    r"auth|login|passw|token|secret|session|crypt|permission|admin|sql|query|route|handler"
    r"|middleware|upload|payment|webhook",
    re.I,
)
TEST_HINTS = re.compile(
    r"(^|/)(tests?|__tests__|spec)/|(^|/)test_[^/]*$|_test\.[a-z]+$|\.(spec|test)\.[a-z]+$"
)


@dataclass(frozen=True)
class SkippedFile:
    path: str
    reason: SkipReason


@dataclass(frozen=True)
class FilterResult:
    kept: list[FileDiff]
    skipped: list[SkippedFile]


@lru_cache(maxsize=512)
def _glob_re(pattern: str) -> re.Pattern[str]:
    out: list[str] = []
    i = 0
    while i < len(pattern):
        if pattern.startswith("**/", i):
            out.append("(?:.*/)?")
            i += 3
            continue
        if pattern.startswith("**", i):
            out.append(".*")
            i += 2
            continue
        c = pattern[i]
        out.append("[^/]*" if c == "*" else "[^/]" if c == "?" else re.escape(c))
        i += 1
    return re.compile("".join(out) + r"\Z")


def glob_match(path: str, pattern: str) -> bool:
    """Gitignore-style glob: ``**`` spans directories; a slash-less pattern matches basenames."""
    pattern = pattern.strip().lstrip("/")
    if not pattern:
        return False
    if _glob_re(pattern).match(path):
        return True
    return "/" not in pattern and _glob_re(pattern).match(PurePosixPath(path).name) is not None


def passes_path_filters(path: str, filters: Sequence[str]) -> bool:
    """CodeRabbit ``path_filters``: ``!glob`` excludes; plain globs make the list an allowlist."""
    includes = [f for f in filters if f and not f.startswith("!")]
    excludes = [f[1:] for f in filters if f.startswith("!")]
    if any(glob_match(path, p) for p in excludes):
        return False
    return not includes or any(glob_match(path, p) for p in includes)


def _new_side_text(f: FileDiff) -> list[str]:
    return [ln.text for h in f.hunks for ln in h.lines if ln.kind == "add"]


def classify(f: FileDiff) -> SkipReason | None:
    """The always-excluded reason for a file, or ``None`` when it is reviewable."""
    p = PurePosixPath(f.path)
    lower = f.path.lower()
    if f.status == "removed":
        return "removed"
    if p.name in LOCKFILES or p.suffix == ".lock":
        return "lockfile"
    if f.is_binary or p.suffix.lower() in BINARY_EXTS:
        return "binary"
    if any(lower.startswith(v) or f"/{v}" in lower for v in VENDORED):
        return "vendored"
    added = _new_side_text(f)
    if ".min." in p.name or any(len(t) > MINIFIED_LINE_CHARS for t in added):
        return "minified"
    head = "\n".join(added[:10])
    if any(m in head for m in GENERATED_MARKERS):
        return "generated"
    return None


def filter_files(files: Sequence[FileDiff], cfg: HootPRConfig) -> FilterResult:
    kept: list[FileDiff] = []
    skipped: list[SkippedFile] = []
    for f in files:
        reason = classify(f)
        if reason is None and not passes_path_filters(f.path, cfg.reviews.path_filters):
            reason = "path_filter"
        if reason is None:
            kept.append(f)
        else:
            skipped.append(SkippedFile(f.path, reason))
    return FilterResult(kept, skipped)


def _changed(f: FileDiff) -> int:
    return f.additions + f.deletions


def _rank(f: FileDiff) -> tuple[int, int, int, str]:
    return (
        0 if SECURITY_HINTS.search(f.path) else 1,
        1 if TEST_HINTS.search(f.path) else 0,
        -_changed(f),
        f.path,
    )


def apply_budget(files: Sequence[FileDiff], *, max_files: int, max_lines: int) -> FilterResult:
    """Keep the best-ranked files within budget (security, then source over tests, then size).

    The survivors keep their original diff order; at least one file is always kept.
    """
    if len(files) <= max_files and sum(_changed(f) for f in files) <= max_lines:
        return FilterResult(list(files), [])
    chosen: set[str] = set()
    used = 0
    skipped: list[SkippedFile] = []
    for f in sorted(files, key=_rank):
        n = _changed(f)
        if len(chosen) < max_files and (used + n <= max_lines or not chosen):
            chosen.add(f.path)
            used += n
        else:
            skipped.append(SkippedFile(f.path, "over_budget"))
    return FilterResult([f for f in files if f.path in chosen], skipped)
